"""Tests for wa_todo.py. Run: python3 -m unittest discover -s deploy/tests -v

The messages database is a copy of a real file written by Sealjay's own
store code (fixtures/sealjay_messages.db, generated by its StoreMessage), and
new rows are written the way Sealjay writes them: INSERT OR REPLACE with
Go's timestamp encoding.
"""
import contextlib
import datetime as dt
import os
import shutil
import sqlite3
import sys
import tempfile
import time
import unittest
from unittest import mock

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
import wa_todo  # noqa: E402

FIXTURE = os.path.join(HERE, "fixtures", "sealjay_messages.db")
IDT = dt.timezone(dt.timedelta(hours=3))


def go_ts(days_ago=0.0):
    """Timestamp text exactly as go-sqlite3 stores a time.Time."""
    t = dt.datetime.now(IDT) - dt.timedelta(days=days_ago)
    return t.strftime("%Y-%m-%d %H:%M:%S.") + "%09d" % (t.microsecond * 1000) + "+03:00"


class FakeModel:
    """Returns scripted ops and records prompts."""

    def __init__(self):
        self.prompts = []
        self.script = []
        self.fail = False

    def __call__(self, prompt):
        self.prompts.append(prompt)
        if self.fail:
            raise RuntimeError("model unavailable")
        return self.script.pop(0) if self.script else []


class FakeMail:
    def __init__(self):
        self.sent = []
        self.mode = "ok"  # ok | fail_before | fail_after_accept

    def __call__(self, subject, body, on_accepted):
        if self.mode == "fail_before":
            raise ConnectionError("smtp down")
        on_accepted()
        self.sent.append(body)
        if self.mode == "fail_after_accept":
            raise ConnectionError("connection dropped during QUIT")


class Base(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.dir)
        self.msgdb = os.path.join(self.dir, "messages.db")
        shutil.copy(FIXTURE, self.msgdb)
        with self.db() as c:
            c.execute("DELETE FROM messages")
        self.cfg = {
            "me_names": ["Ron"],
            "accounts": [{"name": "personal", "messages_db": self.msgdb, "chats": []}],
            "state": os.path.join(self.dir, "state.db"),
            "send_empty": False,
        }
        self.model = FakeModel()
        self.mail = FakeMail()

    @contextlib.contextmanager
    def db(self):
        c = sqlite3.connect(self.msgdb, isolation_level=None)
        try:
            yield c
        finally:
            c.close()

    def put(self, mid, content, days_ago=0.0, chat="g1@g.us"):
        with self.db() as c:  # Sealjay's write path
            c.execute("INSERT OR REPLACE INTO messages (id, chat_jid, sender, content, timestamp, is_from_me) "
                      "VALUES (?, ?, '972500000001', ?, ?, 0)", (mid, chat, content, go_ts(days_ago)))

    def run_once(self):
        return wa_todo.run(self.cfg, {}, self.model, self.mail)

    def processed_ids(self, prompt_index):
        return [m for m in ("m0", "m1", "m2", "m3", "m4", "m5", "LATE", "OLD", "BAD") if '"%s"' % m in self.model.prompts[prompt_index]]


class TestSelection(Base):
    def test_fixture_timestamp_format_is_parsed(self):
        with contextlib.closing(sqlite3.connect("file:%s?mode=ro" % FIXTURE, uri=True)) as c:
            ts, jd = c.execute("SELECT timestamp, julianday(timestamp) FROM messages").fetchone()
        self.assertRegex(ts, r"^\d{4}-\d\d-\d\d \d\d:\d\d:\d\d\.\d{9}\+03:00$")
        self.assertIsNotNone(jd)

    def test_new_message_processed_once(self):
        self.put("m1", "Ron please bring cups")
        self.run_once()
        self.run_once()
        self.run_once()
        self.assertEqual(len(self.model.prompts), 1)

    def test_rowid_reuse_after_delete(self):
        self.put("m1", "first")
        self.put("m2", "second")
        self.run_once()
        with self.db() as c:
            rowid_m2 = c.execute("SELECT rowid FROM messages WHERE id='m2'").fetchone()[0]
            c.execute("DELETE FROM messages WHERE id='m2'")
        self.put("m3", "Ron can you fix the sink")
        with self.db() as c:
            self.assertEqual(c.execute("SELECT rowid FROM messages WHERE id='m3'").fetchone()[0], rowid_m2,
                             "precondition: SQLite reused the ROWID")
        self.run_once()
        self.assertEqual(len(self.model.prompts), 2)
        self.assertEqual(self.processed_ids(1), ["m3"])

    def test_replace_with_new_content_is_reprocessed(self):
        self.put("m1", "Ron bring cups")
        self.run_once()
        self.put("m1", "Ron bring cups")  # re-delivery, same content
        self.run_once()
        self.assertEqual(len(self.model.prompts), 1)
        self.put("m1", "Ron bring cups AND plates")  # edit
        self.run_once()
        self.assertEqual(len(self.model.prompts), 2)
        self.assertIn("AND plates", self.model.prompts[1])

    def test_late_history_sync_inside_window(self):
        self.put("m1", "today")
        self.run_once()
        self.put("LATE", "from five days ago, synced late", days_ago=5)
        self.run_once()
        self.assertEqual(self.processed_ids(1), ["LATE"])

    def test_late_history_sync_outside_window_is_skipped(self):
        # Documented limit: older than lookback_days is ignored.
        self.put("OLD", "from last month", days_ago=30)
        self.run_once()
        self.assertEqual(self.model.prompts, [])

    def test_unparseable_timestamp_included_not_dropped(self):
        with self.db() as c:
            c.execute("INSERT INTO messages (id, chat_jid, sender, content, timestamp, is_from_me) "
                      "VALUES ('BAD', 'g1@g.us', 's', 'weird ts', 'not a time', 0)")
        self.run_once()
        self.assertEqual(self.processed_ids(0), ["BAD"])

    def test_chat_filter(self):
        self.cfg["accounts"][0]["chats"] = ["g1@g.us"]
        self.put("m1", "in scope")
        self.put("m2", "out of scope", chat="other@g.us")
        self.run_once()
        self.assertEqual(self.processed_ids(0), ["m1"])

    def test_batch_limit_carries_over(self):
        for i in range(5):
            self.put("m%d" % i, "msg %d" % i, days_ago=1 - i * 0.01)
        with mock.patch.object(wa_todo, "MAX_MESSAGES", 3):
            orig = wa_todo.fetch_unseen
            with mock.patch.object(wa_todo, "fetch_unseen",
                                   lambda *a, **k: orig(*a, limit=3)):
                self.run_once()
                self.run_once()
                self.run_once()
        self.assertEqual(len(self.model.prompts), 2)
        self.assertEqual(sorted(self.processed_ids(0) + self.processed_ids(1)), ["m0", "m1", "m2", "m3", "m4"])

    def test_restart_does_not_reprocess(self):
        self.put("m1", "Ron bring cups")
        self.model.script = [[{"op": "add", "text": "Bring cups", "chat": "Class parents"}]]
        self.run_once()
        # A new process: new FakeModel, same state file.
        self.model = FakeModel()
        self.run_once()
        self.assertEqual(self.model.prompts, [])
        with contextlib.closing(sqlite3.connect(self.cfg["state"])) as st:
            self.assertEqual(st.execute("SELECT count(*) FROM tasks WHERE status='open'").fetchone()[0], 1)

    def test_model_failure_changes_nothing(self):
        self.put("m1", "Ron bring cups")
        self.model.fail = True
        self.assertEqual(self.run_once(), 1)
        self.model.fail = False
        self.run_once()
        self.assertEqual(len(self.model.prompts), 2, "messages must be retried after a failed model call")

    def test_messages_db_is_never_written(self):
        self.put("m1", "Ron bring cups")
        def snapshot():
            with open(self.msgdb, "rb") as f:
                return f.read()
        before = snapshot()
        self.run_once()
        self.assertEqual(snapshot(), before)


class TestTasks(Base):
    def test_one_message_many_tasks_and_later_cancel(self):
        self.put("m1", "Ron bring cups and plates")
        self.model.script = [[{"op": "add", "text": "Bring cups", "chat": "c"},
                              {"op": "add", "text": "Bring plates", "chat": "c"}]]
        self.run_once()
        self.put("m2", "Dana brings plates instead")
        self.model.script = [[{"op": "cancel", "task_id": "t2", "reason": "Dana brings them"}]]
        self.run_once()
        self.assertIn('"t2"', self.model.prompts[1], "open tasks must be given to the model")
        self.assertIn("DROP t2: Bring plates", self.mail.sent[-1])
        self.assertIn("Bring cups", self.mail.sent[-1])
        self.assertNotIn("- [personal] Bring plates", self.mail.sent[-1])

    def test_ops_for_unknown_or_other_account_tasks_ignored(self):
        self.put("m1", "x")
        self.model.script = [[{"op": "done", "task_id": "t99"}, {"op": "bogus"}, "junk"]]
        self.assertEqual(self.run_once(), 0)


class TestDelivery(Base):
    def test_smtp_failure_keeps_changes_and_does_not_rerun_model(self):
        self.put("m1", "Ron bring cups")
        self.model.script = [[{"op": "add", "text": "Bring cups", "chat": "c"}]]
        self.mail.mode = "fail_before"
        self.assertEqual(self.run_once(), 1)
        self.assertEqual(self.mail.sent, [])
        self.mail.mode = "ok"
        self.run_once()
        self.assertEqual(len(self.model.prompts), 1, "retry must not call the model again")
        self.assertIn("NEW  t1: Bring cups", self.mail.sent[0])
        self.run_once()  # nothing new, send_empty False
        self.assertEqual(len(self.mail.sent), 1)

    def test_failure_after_server_accepted_does_not_duplicate(self):
        self.put("m1", "Ron bring cups")
        self.model.script = [[{"op": "add", "text": "Bring cups", "chat": "c"}]]
        self.mail.mode = "fail_after_accept"
        self.run_once()
        self.mail.mode = "ok"
        self.cfg["send_empty"] = True
        self.run_once()
        self.assertEqual(len(self.mail.sent), 2)
        self.assertNotIn("NEW  t1", self.mail.sent[1])
        self.assertIn("Changes since last digest:\n(none)", self.mail.sent[1])

    def test_failed_digests_accumulate(self):
        self.mail.mode = "fail_before"
        self.put("m1", "a")
        self.model.script = [[{"op": "add", "text": "Task A", "chat": "c"}]]
        self.run_once()
        self.put("m2", "b")
        self.model.script = [[{"op": "add", "text": "Task B", "chat": "c"}]]
        self.run_once()
        self.mail.mode = "ok"
        self.run_once()
        self.assertIn("Task A", self.mail.sent[0])
        self.assertIn("Task B", self.mail.sent[0])

    def test_smtp_send_marks_before_quit_and_tolerates_quit_error(self):
        events = []

        class FakeSMTP:
            def __init__(self, *a, **k): pass
            def starttls(self): events.append("tls")
            def login(self, u, p): events.append("login")
            def send_message(self, m): events.append("data"); return {}
            def quit(self): events.append("quit"); raise ConnectionError("quit failed")

        env = {"SMTP_USER": "a@b", "SMTP_PASS": "p", "MAIL_TO": "a@b"}
        with mock.patch.object(wa_todo.smtplib, "SMTP", FakeSMTP):
            wa_todo.smtp_send(env, "s", "b", lambda: events.append("accepted"))
        self.assertEqual(events, ["tls", "login", "data", "accepted", "quit"])

    def test_smtp_refused_recipient_is_a_failure(self):
        class FakeSMTP:
            def __init__(self, *a, **k): pass
            def starttls(self): pass
            def login(self, u, p): pass
            def send_message(self, m): return {"a@b": (550, b"no")}
            def quit(self): pass

        accepted = []
        env = {"SMTP_USER": "a@b", "SMTP_PASS": "p", "MAIL_TO": "a@b"}
        with mock.patch.object(wa_todo.smtplib, "SMTP", FakeSMTP):
            with self.assertRaises(Exception):
                wa_todo.smtp_send(env, "s", "b", lambda: accepted.append(1))
        self.assertEqual(accepted, [])


class TestConfig(unittest.TestCase):
    def test_placeholder_mail_env_is_not_configured(self):
        self.assertFalse(wa_todo.mail_configured({"SMTP_USER": "you@gmail.com", "SMTP_PASS": "gmail-app-password", "MAIL_TO": "you@gmail.com"}))
        self.assertFalse(wa_todo.mail_configured({}))
        self.assertTrue(wa_todo.mail_configured({"SMTP_USER": "r@x.com", "SMTP_PASS": "abcd", "MAIL_TO": "r@x.com"}))


if __name__ == "__main__":
    unittest.main()
